[package]
name = "passwordgenerator"
version = "0.5.5"
edition = "2021"
license = "CC-BY-SA-4.0"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_10"] }
glib = "0.20"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gio = "0.20"

